version: '3.9'
services:
    php:
        build:
            context: docker/
            dockerfile: php.Dockerfile
        working_dir: /app
        volumes:
            - './:/app'
        command: ['sh']

