name: Setup PHP
description: Setup PHP build
runs:
    using: composite
    steps:
        -   name: Install PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.2'

        -   id: install-composer-dependencies
            name: Install composer dependencies
            run: php composer.phar install --ansi
            shell: bash
